// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Support both new format (sb_publishable_*) and legacy JWT format
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ||
                          import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
                          import.meta.env.VITE_SUPABASE_API_KEY;

const createFallbackClient = () => ({
  storage: {
    from: () => ({
      upload: async () => ({ error: new Error('Supabase is not configured') }),
      getPublicUrl: () => ({ data: { publicUrl: '' } }),
    }),
  },
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: any =
  SUPABASE_URL && SUPABASE_ANON_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
        auth: {
          storage: typeof window !== 'undefined' ? window.localStorage : undefined,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : createFallbackClient();
